{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-dom-api-compat",
    "version": "2.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-dom-api-compat-2.0.21.klib",
          "url": "kotlin-dom-api-compat-2.0.21.klib",
          "size": 963137,
          "sha512": "6c00624e42e04d0f5ee5ba7fb9a25f6d27f73669074c7193fd29e31ddc664b086e47f293abcded5137c1e12c841e6127b183c59119eed015d26bdc680b75f0be",
          "sha256": "1e5375ff43a48af6e9f85545831352cf507e8c37b119fb9a7a3ef00dba120e3e",
          "sha1": "537dbda0c5c5ee06c81b2c0d1f466df60d810e3f",
          "md5": "db59953a50b554507d5dbbf7f93cf414"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-dom-api-compat-2.0.21.klib",
          "url": "kotlin-dom-api-compat-2.0.21.klib",
          "size": 963137,
          "sha512": "6c00624e42e04d0f5ee5ba7fb9a25f6d27f73669074c7193fd29e31ddc664b086e47f293abcded5137c1e12c841e6127b183c59119eed015d26bdc680b75f0be",
          "sha256": "1e5375ff43a48af6e9f85545831352cf507e8c37b119fb9a7a3ef00dba120e3e",
          "sha1": "537dbda0c5c5ee06c81b2c0d1f466df60d810e3f",
          "md5": "db59953a50b554507d5dbbf7f93cf414"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-dom-api-compat-2.0.21-sources.jar",
          "url": "kotlin-dom-api-compat-2.0.21-sources.jar",
          "size": 72455,
          "sha512": "df96cb7c4c3b44c2196754b4324f18780573a32bdf57d9edaac8757024e78ce88e473f35b3a369e92abd783a81fc30648f6ab616e6c2e0348c2be376f0c08752",
          "sha256": "172b97b331536a075cc0eb87fe8645c816150227b2fec55a4bfd85c6238a1c44",
          "sha1": "cf030d29729e77a251b90ade274a9d0487c2b689",
          "md5": "0221cc20c60045120be84eea08259f27"
        }
      ]
    }
  ]
}
