{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.0.21/kotlin-test-2.0.21.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-js-2.0.21.klib",
          "url": "kotlin-test-js-2.0.21.klib",
          "size": 62016,
          "sha512": "f0ae8aada1a1d4ddd00f4d64c72c738651de9d1c48a3ff3134a1cd8353278c6b75e675997f27c6338ee5457ddd2dc2131e5767ecb9dc2a3639990bd9d582dfd4",
          "sha256": "7e99c257d410812111dc78f6684928333d69684e39423abb30453de96679de07",
          "sha1": "dc68d22e94e9c346947d6eb9c9c7e21834accc40",
          "md5": "83e9f84d6829247e823976e44c904bb9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-js-2.0.21.klib",
          "url": "kotlin-test-js-2.0.21.klib",
          "size": 62016,
          "sha512": "f0ae8aada1a1d4ddd00f4d64c72c738651de9d1c48a3ff3134a1cd8353278c6b75e675997f27c6338ee5457ddd2dc2131e5767ecb9dc2a3639990bd9d582dfd4",
          "sha256": "7e99c257d410812111dc78f6684928333d69684e39423abb30453de96679de07",
          "sha1": "dc68d22e94e9c346947d6eb9c9c7e21834accc40",
          "md5": "83e9f84d6829247e823976e44c904bb9"
        }
      ]
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-test-js-2.0.21-sources.jar",
          "url": "kotlin-test-js-2.0.21-sources.jar",
          "size": 17582,
          "sha512": "6ce0bf0039c6ad6b010bbf788fc7ba551f3a5775547bd427fbf08419abc67b0cd50bd93f6991177c0aad77ef2896f064edea0c1ac7b5c6a2c6ad66c5e6ad383b",
          "sha256": "e79ab6f8d42509bf022a022dd4a2657efa1e48ea05529104c388afde9829a77a",
          "sha1": "e75fd2e9b1bab67162539e725c0f0be6c6fdfbfc",
          "md5": "5d11d849d654a304d2e0131ee1184ef8"
        }
      ]
    }
  ]
}
