{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-stdlib/2.0.21/kotlin-stdlib-2.0.21.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-stdlib",
    "version": "2.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-stdlib-js-2.0.21.klib",
          "url": "kotlin-stdlib-js-2.0.21.klib",
          "size": 2663694,
          "sha512": "cc46782a3e992069a84176125339dc1ab3f8817a4044cddae0aea11c4a0d39a0db87a01e0eba43cad3847eb19cac1848239a46ee7ae1d8e3b9f77c732ee380b5",
          "sha256": "3fa652b28334769aa06fdb994b2da6cc3851a307c1de66e40a1655eba736c14e",
          "sha1": "08047778f196f3cdc817f1e90eb45f08b4837ba9",
          "md5": "8789c0760b2a305150d98dd550680aed"
        }
      ]
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-stdlib-js-2.0.21.klib",
          "url": "kotlin-stdlib-js-2.0.21.klib",
          "size": 2663694,
          "sha512": "cc46782a3e992069a84176125339dc1ab3f8817a4044cddae0aea11c4a0d39a0db87a01e0eba43cad3847eb19cac1848239a46ee7ae1d8e3b9f77c732ee380b5",
          "sha256": "3fa652b28334769aa06fdb994b2da6cc3851a307c1de66e40a1655eba736c14e",
          "sha1": "08047778f196f3cdc817f1e90eb45f08b4837ba9",
          "md5": "8789c0760b2a305150d98dd550680aed"
        }
      ]
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-stdlib-js-2.0.21-sources.jar",
          "url": "kotlin-stdlib-js-2.0.21-sources.jar",
          "size": 638776,
          "sha512": "66adf12554643e17ec985ac87593344319cf14fae73bd0ded676b35b6561dc9b39b87304d4eb8cb7981c359df004eddc1a72f9b256d5ce92d1d30cd4c2ef760f",
          "sha256": "0b185b44d68d017f4a57f9e47c3944337ff9760a48be4d4310a534d03a1fd70f",
          "sha1": "5ebaf155ff497540bc6b1d80c907c91183bb97e9",
          "md5": "f1b32af4787ee04038e55a67f519df2b"
        }
      ]
    }
  ]
}
