{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.7.3/kotlinx-serialization-json-1.7.3.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-macosarm64-1.7.3.klib",
          "size": 304860,
          "sha512": "fd1e3020e510fd9c04acf38da3a6cf71bd2c78a5403b84dd5fc8887cef21dbb5cbb2f3fdad2ec2e66d7b8ca53dac008899fe4e9d1f241691c66324951a02cc61",
          "sha256": "8697b7be182fe7916b6043a8ebdd381e96bf9dec0a181e5eba87acf61b97c5a8",
          "sha1": "a0a41dfbab2d20d1cc94a98cdd11ff4bcb1de403",
          "md5": "6324fef7a6144c22d12d98560ef40d9f"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-macosarm64-1.7.3-sources.jar",
          "url": "kotlinx-serialization-json-macosarm64-1.7.3-sources.jar",
          "size": 82307,
          "sha512": "ac6eb31c8b4999861587b48cdce462f4c122d41440bef0c2109a1bd14b4235ea0a9d4d250c53d753850aceaf405e7815b4ea5e25701659e762be0adb4d18fc01",
          "sha256": "b6c600f6eded02eb49ac9a40c0ca580295e73f5bb5f7ec0fa9f6b2541ad66182",
          "sha1": "3416cf675640db40f952a4e9605161b8317916e9",
          "md5": "0ff2ad731fda5d11f0ad0c20bdc93d4f"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-macosarm64-1.7.3-metadata.jar",
          "url": "kotlinx-serialization-json-macosarm64-1.7.3-metadata.jar",
          "size": 261,
          "sha512": "e25b180d81f67de5d1f0de64a6e1fcd4c9dfe87cf167db9dabda5f7cac0a080c7a5b3d203c930f68fc9a660928424b5f3bef47cfaefa75d3808cff4d990915f6",
          "sha256": "688ad1bfc9791d5ddb11aef3557bdb974443b323cc35d5c9d81b95a4cbd24cbd",
          "sha1": "6f8f993e182721725931718eb56de90675e7cd28",
          "md5": "38383b671541fbef1414b3075707e3c2"
        }
      ]
    }
  ]
}
