{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.7.3/kotlinx-serialization-json-1.7.3.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-linuxx64-1.7.3.klib",
          "size": 304836,
          "sha512": "67f132aa04915927bdaa2a432312dc99510020654cc27156d06f5c1a38738e59c3fb1aabe89818f5b29f476cb705a64381f3aa486a1b44fec362f36184e063a7",
          "sha256": "232f2c2bd90c0a3c187c944d4c004b3eac45323a508c354d6fa3b9d4662ed87d",
          "sha1": "bf3429a0d152992cf043f963053b202cdd97340e",
          "md5": "01703318d8fcf134365ab2691cc4706f"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-linuxx64-1.7.3-sources.jar",
          "url": "kotlinx-serialization-json-linuxx64-1.7.3-sources.jar",
          "size": 82307,
          "sha512": "ac6eb31c8b4999861587b48cdce462f4c122d41440bef0c2109a1bd14b4235ea0a9d4d250c53d753850aceaf405e7815b4ea5e25701659e762be0adb4d18fc01",
          "sha256": "b6c600f6eded02eb49ac9a40c0ca580295e73f5bb5f7ec0fa9f6b2541ad66182",
          "sha1": "3416cf675640db40f952a4e9605161b8317916e9",
          "md5": "0ff2ad731fda5d11f0ad0c20bdc93d4f"
        }
      ]
    }
  ]
}
